"""
Patient AI trusted-results summary — read-only orchestration service.

Single responsibility: given an authenticated patient, build a read-only,
AI-generated plain-language summary of that patient's own TRUSTED
TestResult data (VERIFIED or CORRECTED only), and return it. This is a
strictly read-only feature layered on top of the existing trust
architecture — it never creates, mutates, or deletes anything.

Trust boundary (enforced end-to-end by this module):

    UPLOAD -> EXTRACTION -> CANDIDATES -> DOCTOR VERIFICATION
        -> TestResult -> AI SUMMARY

    NOT: AI SUMMARY -> verification

Concretely:
* The only database read this module performs is
  app.services.patient_result_service.get_patient_trusted_results, the
  SAME function GET /patient/results already uses — no new query against
  CandidateResult, Report, or any other table is added here. There is
  exactly one code path that decides "what counts as trusted", and this
  module reuses it rather than re-implementing it.
* CandidateResult, PENDING candidates, REJECTED candidates, raw Gemini
  extraction output, OCR/extracted report text, and storage files are
  never read by this module at all.
* If the patient has zero trusted TestResult rows, Gemini is NEVER
  called — see get_patient_result_summary's empty-state short-circuit.
* This module never calls db.add/db.commit/db.delete. It has no way to
  mutate TestResult.status, CandidateResult.verification_status, or
  create a VerificationHistory row — it doesn't import the symbols that
  would let it, and never receives a mutable ORM session reference it
  writes through.
* The disclaimer text returned to the client is a fixed, server-owned
  constant (_DISCLAIMER below) — never something Gemini can omit or
  reword.
"""
import uuid
from datetime import datetime, timezone

from sqlalchemy.orm import Session

from app.schemas.summary import PatientResultSummaryResponse, SummaryInputResult
from app.services.gemini_summary_service import (
    GeminiSummaryError,
    generate_summary_from_trusted_results,
)
from app.services.patient_result_service import get_patient_trusted_results

# Fixed, deterministic empty-state message — returned verbatim whenever
# the patient has no VERIFIED/CORRECTED TestResult rows. Gemini is never
# called for this response (see get_patient_result_summary).
_EMPTY_STATE_MESSAGE = "No trusted laboratory results are available for an AI summary yet."

# Always appended server-side, never generated by Gemini, so this framing
# can never be silently dropped from a response.
_DISCLAIMER = (
    "This is an AI-generated summary of your verified and corrected "
    "laboratory results only. It is not a diagnosis and is not medical "
    "advice. Always talk to your doctor about your results."
)


class SummaryGenerationError(Exception):
    """Raised when the summary cannot be produced (Gemini not configured,
    request failure, or an invalid response). Always carries a message
    that is already safe to show to the client — callers must not wrap
    or re-derive it from a raw exception."""
    pass


def _to_summary_input(test_result) -> SummaryInputResult:
    """Reduce one trusted TestResult ORM row to only the fields Gemini is
    allowed to see. Mirrors the same "no internal identifiers" boundary
    already enforced by app.schemas.result.PatientTestResultResponse —
    this function additionally drops even the id fields that response
    does include (id, canonical_test), since Gemini needs none of them.
    """
    return SummaryInputResult(
        status=test_result.status,
        test_name=(
            test_result.canonical_test.display_name
            if test_result.canonical_test is not None
            else test_result.test_name
        ),
        normalized_value=test_result.normalized_value,
        normalized_unit=test_result.normalized_unit,
        raw_value=test_result.raw_value,
        reference_range_lower=test_result.reference_range_lower,
        reference_range_upper=test_result.reference_range_upper,
        abnormality_status=test_result.abnormality_status,
        result_date=test_result.result_date,
    )


def get_patient_result_summary(
    db: Session, patient_id: uuid.UUID
) -> PatientResultSummaryResponse:
    """Build a read-only AI summary of the authenticated patient's own
    trusted TestResult rows.

    Strictly read-only: performs one query (via
    get_patient_trusted_results, the same function the existing
    GET /patient/results endpoint uses) and otherwise only calls the
    stateless Gemini boundary. No db.add/commit/delete anywhere in this
    module. patient_id must come from the authenticated session (see
    routers/results.py) — this function performs no authentication or
    role check of its own, matching the existing pattern used by
    get_patient_trusted_results.

    Empty-state rule: if the patient has zero VERIFIED/CORRECTED
    TestResult rows, this returns the deterministic empty-state response
    immediately and Gemini is NEVER called — PENDING candidates (which
    never produce a TestResult row to begin with) can therefore never
    reach Gemini through this path.

    Raises SummaryGenerationError if trusted results exist but Gemini
    could not produce a valid summary (not configured, request failure,
    or schema-invalid response). The message is always safe to return to
    the client as-is.
    """
    trusted_results = get_patient_trusted_results(db, patient_id)

    if not trusted_results:
        return PatientResultSummaryResponse(
            has_trusted_results=False,
            result_count=0,
            observations=[_EMPTY_STATE_MESSAGE],
            disclaimer=_DISCLAIMER,
            generated_at=None,
        )

    safe_input = [_to_summary_input(tr) for tr in trusted_results]

    try:
        gemini_response = generate_summary_from_trusted_results(safe_input)
    except GeminiSummaryError as exc:
        raise SummaryGenerationError(str(exc)) from None

    return PatientResultSummaryResponse(
        has_trusted_results=True,
        result_count=len(trusted_results),
        observations=[item.text for item in gemini_response.observations],
        disclaimer=_DISCLAIMER,
        generated_at=datetime.now(timezone.utc),
    )
