"""
Schemas for the read-only AI trusted-results summary feature
(GET /patient/results/summary).

Trust boundary (see app/models/extraction.py:TestResult docstring and
app.services.patient_result_service):

    Gemini -> CandidateResult (PENDING) -> Doctor review
        -> VERIFY / CORRECT -> TestResult -> patient trusted results
        -> AI reads ONLY the trusted TestResult rows -> AI summary

This module defines three distinct shapes, deliberately kept separate:

1. `SummaryInputResult` — the safe, server-constructed representation of
   ONE trusted TestResult that is allowed to reach Gemini. Built only
   from fields already exposed to patients via
   app.schemas.result.PatientTestResultResponse (see that module's
   docstring for the same "never send internal identifiers" rule).
   Never includes ids, doctor_id, candidate_result_id, extraction_run_id,
   correction_note, storage paths, or hashes.

2. `GeminiSummaryResponse` / `GeminiSummaryObservation` — the ONLY shape
   Gemini's response for this feature is allowed to take. Used both as
   the structured-output `response_schema` passed to the SDK and, again
   independently, to validate whatever text comes back before anything
   touches the response the client receives (the backend never trusts
   the model just because structured output was requested — same
   pattern as app.schemas.gemini_extraction). `extra="forbid"` means any
   field Gemini invents beyond this schema causes validation to fail
   rather than being silently accepted.

3. `PatientResultSummaryResponse` — the final response returned by
   GET /patient/results/summary. The disclaimer is always a fixed,
   server-controlled string (see app.services.patient_summary_service)
   — it is never generated by Gemini, so the "this is not a diagnosis"
   framing can never be omitted by a model response.
"""
import uuid
from datetime import date, datetime
from decimal import Decimal

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.models.extraction import AbnormalityStatus, TestResultStatus


class SummaryInputResult(BaseModel):
    """One trusted TestResult, reduced to only the fields Gemini needs to
    write a plain-language summary. Constructed server-side in
    app.services.patient_summary_service from TestResult rows already
    scoped to the authenticated patient — never accepts client input and
    is never itself accepted as request input.
    """

    model_config = ConfigDict(extra="forbid")

    # VERIFIED or CORRECTED only — see TestResultStatus. Included so the
    # model can note when a value reflects a doctor's correction, but it
    # is never itself something the model is asked to change.
    status: TestResultStatus
    test_name: str
    normalized_value: Decimal | None = None
    normalized_unit: str | None = None
    raw_value: str
    reference_range_lower: Decimal | None = None
    reference_range_upper: Decimal | None = None
    abnormality_status: AbnormalityStatus
    result_date: date | None = None


class GeminiSummaryObservation(BaseModel):
    """One factual observation about the supplied trusted results.
    Gemini must never invent a value here (enforced by the fixed system
    instruction in app.services.gemini_summary_service); this schema
    only enforces shape, not truthfulness."""

    model_config = ConfigDict(extra="forbid")

    text: str

    @field_validator("text")
    @classmethod
    def _must_be_non_empty(cls, value: str) -> str:
        stripped = value.strip()
        if not stripped:
            raise ValueError("must not be empty")
        return stripped


class GeminiSummaryResponse(BaseModel):
    """The full structured response Gemini must return for one summary
    request. An empty `observations` list is a legitimate outcome; it is
    not, by itself, a validation failure."""

    model_config = ConfigDict(extra="forbid")

    observations: list[GeminiSummaryObservation] = Field(default_factory=list)


class PatientResultSummaryResponse(BaseModel):
    """Response body for GET /patient/results/summary.

    `disclaimer` is always populated by the server (never by Gemini —
    see module docstring) so the "AI-generated, not a diagnosis" framing
    can never be silently dropped. `observations` is empty and
    `generated_at` is None whenever `has_trusted_results` is False —
    Gemini is never called in that case (see
    app.services.patient_summary_service.get_patient_result_summary).
    """

    model_config = ConfigDict(from_attributes=True)

    has_trusted_results: bool
    result_count: int
    observations: list[str]
    disclaimer: str
    generated_at: datetime | None
